### ISSUE TITLE
Author Name

### ISSUE THREAD

**Issue by NikV** [jameskoster/highwind#32]
Any plans for adding an author name under or over the date before the post on an archive page?

**Comment by jameskoster** [comment]
Hadn't thought about it as Highwind was originally built to be used on my personal blog.

Suppose I could add it with a filter to remove :-)

**Comment by spacesteph** [comment]
I was trying to figure out the same thing... we're using it for a multi-author blog (hosted on wordpress.com) and need to have authors names listed with the articles (on the archive page would be nice too) 

Are you planning to add this, or do I need to go theme-hunting? 

PS LOVE the theme otherwise, it was lovely to customize and does everything we need it to except for this one little thing. :)

**Comment by jameskoster** [comment]
I'll probably add it in the next release. Until then you can always hook in a custom function to do this yourself ;-)

**Comment by spacesteph** [comment]
Thanks! Alas, I don't have that kind of mojo, and at the moment don't have access to someone who does. If I did, I'd have also figured out how to put a page menu across the top like you have implemented on your site :) 

PS: don't know if you like to collect examples, but here's our blog currently using your theme: http://frontierfields.wordpress.com/

**Comment by jameskoster** [comment]
@spacesteph Menus are added using WordPress' native menu feature: http://codex.wordpress.org/WordPress_Menu_User_Guide

Thanks for the link, I'll check it out :-)

**Comment by spacesteph** [comment]
Hi James,

First, thank you for adding this feature!

Second, since I'm using your Highwind theme as hosted on Wordpress.com, how do I access it? I can't find a setting or a switch anywhere that activates the authors name to display with the posts. Do I need to contact Wordpress directly about updating their build, or am I missing a setting somewhere?

 -- Stephanie

---

Stephanie Smith
Lead Graphic Designer
Office of Public Outreach
Space Telescope Science Institute

http://www.hubblesite.org
http://www.webbtelescope.org

**Comment by jameskoster** [comment]
@spacesteph Unfortunately the wordpress.com version is slightly different and wasn't actually built by me. I'd recommend contacting the .com team asking them to update their version to match the .org one.
